"""update_new_table3

Revision ID: d7d840cb6e75
Revises: b23199001293
Create Date: 2025-12-15 17:44:52.766499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7d840cb6e75'
down_revision: Union[str, Sequence[str], None] = 'b23199001293'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scripts', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('scripts', sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('scripts', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_scripts_started_at'), 'scripts', ['started_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scripts_started_at'), table_name='scripts')
    op.drop_column('scripts', 'completed_at')
    op.drop_column('scripts', 'started_at')
    op.drop_column('scripts', 'created_at')
    # ### end Alembic commands ###
