"""update_new_table2

Revision ID: b23199001293
Revises: 
Create Date: 2025-12-10 17:37:35.040304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b23199001293'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scripts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', name='scriptstatus'), nullable=False),
    sa.Column('k8s_job_name', sa.String(length=256), nullable=True),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scripts'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scripts')
    # ### end Alembic commands ###
